name: Gitleaks Secret Scan

on:
  push:

jobs:
  gitleaks:
    name: Detect leaks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --source . --no-git --redact
